---
plugins:
  eslint:
    enabled: true
    config:
      config: .eslintrc
  fixme:
    enabled: true
  git-legal:
    enabled: true
ratings:
  paths:
    - '*.js'
exclude_paths:
  - coverage/
  - dist/
  - node_modules/
  - test*
