version: '3'

services:

  node: &node
    image: 'node:11'
    entrypoint: node
    volumes:
      - ./:/src
    working_dir: /src

  npm: &npm
    <<: *node
    entrypoint: npm

  test:
    <<: *npm
    command: test
