version: '3'

services:

  node: &node
    image: node:11
    entrypoint: node
    volumes:
      - ./:/src
      - node_modules:/src/node_modules
    working_dir: /src

  npm: &npm
    <<: *node
    entrypoint: npm

  codeclimate:
    image: codeclimate/codeclimate
    command: analyze
    volumes:
      - $PWD:/code
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/cc:/tmp/cc
    environment:
      - CODECLIMATE_CODE=$PWD
      #- CODECLIMATE_DEBUG=1

  test:
    <<: *npm
    command: test

volumes:
  node_modules:
